spring:
  application:
    name: config-server
  profiles:
    active: native # Это отключает поиск Git по умолчанию
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config/telemetry/{application}
server:
  port: 8888